export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_REQUEST_SENT = 'MESSAGE_REQUEST_SENT';
export const MESSAGE_REQUEST_FAILED = 'MESSAGE_REQUEST_FAILED';
export const SET_COLOR = 'SET_COLOR';
export const SET_CONTAINER = 'SET_CONTAINER';